// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yeizshpwaezgphfghugr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllaXpzaHB3YWV6Z3BoZmdodWdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NjYyNTUsImV4cCI6MjA1NzU0MjI1NX0.QxgVN694k-0KhA1MA5AWqD6HFjJ7KmrB2ra3KT38xAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);